version: '2.28'
services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  user-service:
    build: './user_service'
    ports:
      - '8001:8001'
    depends_on:
      - mongo
    networks:
      - backend-network

  blog-service:
    build: './blog_service'
    ports:
      - '8002:8002'
    depends_on:
      - mongo
    networks:
      - backend-network

  tour-service:
    build: './tour_service'
    ports:
      - '8003:8003'
    depends_on:
      - mongo
    networks:
      - backend-network

  api-gateway:
    build: './api_gateway'
    ports:
      - '8000:8000'
    depends_on:
      - user-service
      - blog-service
      - tour-service
    networks:
      - backend-network

volumes:
  mongo-data:

networks:
  backend-network:
    driver: bridge
